language: python
python:
  - 2.7
  - 3.3

install:
  - python setup.py install
  - pip install -r dev-requirements.txt

script: coverage run setup.py -q nosetests

after_success: coveralls

notifications:
  email: false
